### ISSUE TITLE
Move to IPFS Shipyard

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-postmsg-proxy#36]
@alanshaw how do you feel about moving this library to https://github.com/ipfs-shipyard/ ?

It is already used by two projects there:
- https://github.com/ipfs-shipyard/ipfs-companion
- https://github.com/ipfs-shipyard/service-worker-gateway

**Comment by alanshaw** [comment]
resolved in https://github.com/ipfs-shipyard/ipfs-postmsg-proxy/commit/c61d66f8cb46bcd331aae4633aa4164685e29864
